name: Publish Features

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v7

      - name: Login to GHCR
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR: ${{ github.actor }}
        run: echo "$TOKEN" | docker login ghcr.io -u "$ACTOR" --password-stdin

      - uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          publish-features: true
          base-path-to-features: ./src
          generate-docs: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
